# permissions for end users to view basicreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basicreplicaset-viewer-role
rules:
- apiGroups:
  - paternal.codefactory.hu
  resources:
  - basicreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paternal.codefactory.hu
  resources:
  - basicreplicasets/status
  verbs:
  - get
