# permissions for end users to edit basicreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basicreplicaset-editor-role
rules:
- apiGroups:
  - paternal.codefactory.hu
  resources:
  - basicreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paternal.codefactory.hu
  resources:
  - basicreplicasets/status
  verbs:
  - get
