# permissions for end users to view basicdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basicdeployment-viewer-role
rules:
- apiGroups:
  - paternal.codefactory.hu
  resources:
  - basicdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paternal.codefactory.hu
  resources:
  - basicdeployments/status
  verbs:
  - get
